name: Deploy Locally via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Application
        run: |
          # Tambahkan pengecualian keamanan Git untuk folder ini
          git config --global --add safe.directory /www/wwwroot/tracker-app

          # 1. Pindah ke folder proyek tracker-app
          cd /www/wwwroot/tracker-app

          # 2. Tarik kode terbaru
          git pull origin main

          # 3. Sinkronisasi dependencies & database
          npm install
          npx prisma generate
          npx prisma db push

          # 4. Build Next.js
          npm run build

          # 5. Reload PM2
          pm2 reload server || pm2 restart server